### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ArmeF97** [PoliNetwork/PoliNetworkBotPython#1]
Todo list

- [X] 1. Link di ingresso
- [x] 2. Sistema di recensioni gruppi/corsi
- [x] 3A. Moderazione: Anti-spam
- [x] 3B. Moderazione: Anti-parole bandite
- [x] 3C. Moderazione: Ban, mute, unban, unmute, banAll
- [x] 4A. Link a materiale scolastico (aggiungi)
- [x] 4B. Link a materiale scolastico (rimuovi)
- [x] 4C. Link a materiale scolastico (ottieni)
- [x] 5. Link utili a: FAQ, bot aule
- [x] 6. Link gruppo oggetti smarriti
- [x] 7. Conferma di ban/mute (ecc...) in messaggio privato di azione eseguita con successo
- [x] 8. Quando la reviews list è vuota bisogna evitare di mandare il file HTML

**Comment by ArmeF97** [comment]
Per l'antiflood aspettiamo le nuove bot api
